import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { ToastContainer } from 'react-toastify';
import FontAwsomeConfig from './fontAwsomeConfig';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <FontAwsomeConfig/>
      </head>
      <body className={inter.className}>
        <Header />
        {children}
        <ToastContainer 
          position="bottom-right"
          autoClose={3000}
          closeOnClick
          draggable
        />
        <Footer />
      </body>
    </html>
  );
}
